### PR TITLE
dotnetcore

### PR DESCRIPTION
**Pull request by Dirtypaws**
#2 Rebuilt the solution like Nancy to allow linked code files across xproj and csproj. Had some merge conflicts with the nuget updates, but, they should be working correctly now.

### CODE REVIEW

**Comment by efaruk** [comment]
Well done Matt, you are just amazing, I'm really happy to work with you...

**Comment by Dirtypaws** [comment]
I should also mention - one other thing I did in there. Because my local Redis instance is at a different IP. I abstracted that out into two helper files in the Demo and the tests. Because the two frameworks have different conventions for using config files they each maintain their own helper files to read the config respective to the environment.

Example:
In the .NET framework demo project there's a Helper/SettingsHelper.cs to get the Redis instance:
```C#
public static string Redis => ConfigurationManager.AppSettings["redis"]
```
While the same file in the dotnetcore project looks like this:
```C#
        static string _env;
        static string Env => _env ?? (_env = Environment.GetEnvironmentVariable("env"));

        static bool IsDevelopment => Env == "Dev";

        public static IConfigurationRoot Configuration
        {
            get
            {
                var builder = new ConfigurationBuilder()
                    .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
                    .AddJsonFile($"appsettings.{Env}.json", optional: true);

                if (IsDevelopment) builder.AddUserSecrets();

                builder.AddEnvironmentVariables();
                return builder.Build();
            }
        }

        public static string Redis => Configuration["redis"];
```

That's probably something that it should do anyway - and the nuget can provide it's own configuration settings file when installed - like NLog. So essentially, the Framework solutions are in the .Build folders and maintain their csproj file as well as any framework specific files and their packages.config. the non '.build' folders house the xproj files and their project.json files.

**Comment by efaruk** [comment]
Thank you very much Matt...

**Comment by efaruk** [comment]
Also i'm trying to create basic flows and drawings right now...

**Comment by Dirtypaws** [comment]
Mind if I merge this pull request? It'll help me from dealing with conflicts to nuget updates and such.

**Comment by efaruk** [comment]
Of course keep going...

**Comment by efaruk** [comment]
I was looked forward for that one ;)

**Pull request merged**
